<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\OrgNet.Infrastructure\OrgNet.Infrastructure.csproj" />
    <ProjectReference Include="..\OrgNet.Domain\OrgNet.Domain.csproj" />
    <ProjectReference Include="..\OrgNet.Shared\OrgNet.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>31d59141-9d6d-4804-aea8-a9ff8d8be75d</UserSecretsId>
  </PropertyGroup>

</Project>
